- name: Desplegar aplicación en Kubernetes
  hosts: "locahost"
  tasks:
    - block:
      - name: Mostrar mensaje si el target es localhost
        debug:
          msg: "Aplicando el deploy del user-server en localhost"

      - name: Deploy application using Helm
        community.kubernetes.helm:
          name: "my-user-server-release"
          chart: "./charts/user-server"
          values: "./charts/user-server/values.yaml"
      # - name: Aplicar el Deployment en Kubernetes
      #   community.kubernetes.k8s:
      #     state: present
      #     definition: "{{ lookup('file', './../../k8s/' + {{ service }} + '/deployment.yaml') }}"
    when: target_group == 'localhost'